/*
* generated by Xtext
*/
package org.xtext.smokingtext.diagramclass.ui.contentassist;

import org.xtext.smokingtext.diagramclass.ui.contentassist.AbstractDiagramClassProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DiagramClassProposalProvider extends AbstractDiagramClassProposalProvider {

}
