/**
 * generated by Xtext
 */
package org.xtext.smokingtext.diagramclass.validation;

import org.xtext.smokingtext.diagramclass.validation.AbstractDiagramClassValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DiagramClassValidator extends AbstractDiagramClassValidator {
}
