/*
 * generated by Xtext
 */
package org.xtext.smokingtext.diagramclass.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.smokingtext.diagramclass.services.DiagramClassGrammarAccess;

public class DiagramClassParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DiagramClassGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.smokingtext.diagramclass.parser.antlr.internal.InternalDiagramClassParser createParser(XtextTokenStream stream) {
		return new org.xtext.smokingtext.diagramclass.parser.antlr.internal.InternalDiagramClassParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DiagramClassGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DiagramClassGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
