/*
 * generated by Xtext
 */
package org.xtext.smokingtext.diagramclass.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DiagramClassUiModule extends org.xtext.smokingtext.diagramclass.ui.AbstractDiagramClassUiModule {
	public DiagramClassUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
