/*
 * generated by Xtext
 */
package org.xtext.smokingtext.diagramclass;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DiagramClassUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.smokingtext.diagramclass.ui.internal.DiagramClassActivator.getInstance().getInjector("org.xtext.smokingtext.diagramclass.DiagramClass");
	}
	
}
