/*
 * generated by Xtext
 */
package org.xtext.smokingtext.diagramclass;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DiagramClassRuntimeModule extends org.xtext.smokingtext.diagramclass.AbstractDiagramClassRuntimeModule {

}
