/*
 * generated by Xtext
 */
package org.xtext.smokingtext.diagramclass.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.smokingtext.diagramclass.diagramClass.Abstract;
import org.xtext.smokingtext.diagramclass.diagramClass.Attribute;
import org.xtext.smokingtext.diagramclass.diagramClass.BiRelation;
import org.xtext.smokingtext.diagramclass.diagramClass.Dependancy;
import org.xtext.smokingtext.diagramclass.diagramClass.DiagramClassPackage;
import org.xtext.smokingtext.diagramclass.diagramClass.Enumeration;
import org.xtext.smokingtext.diagramclass.diagramClass.Interface;
import org.xtext.smokingtext.diagramclass.diagramClass.Method;
import org.xtext.smokingtext.diagramclass.diagramClass.Model;
import org.xtext.smokingtext.diagramclass.diagramClass.paramIn;
import org.xtext.smokingtext.diagramclass.services.DiagramClassGrammarAccess;

@SuppressWarnings("all")
public class DiagramClassSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DiagramClassGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == DiagramClassPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case DiagramClassPackage.ABSTRACT:
				sequence_Abstract(context, (Abstract) semanticObject); 
				return; 
			case DiagramClassPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case DiagramClassPackage.BI_RELATION:
				sequence_BiRelation(context, (BiRelation) semanticObject); 
				return; 
			case DiagramClassPackage.CLASS:
				sequence_Class(context, (org.xtext.smokingtext.diagramclass.diagramClass.Class) semanticObject); 
				return; 
			case DiagramClassPackage.DEPENDANCY:
				sequence_Dependancy(context, (Dependancy) semanticObject); 
				return; 
			case DiagramClassPackage.ENUMERATION:
				sequence_Enumeration(context, (Enumeration) semanticObject); 
				return; 
			case DiagramClassPackage.INTERFACE:
				sequence_Interface(context, (Interface) semanticObject); 
				return; 
			case DiagramClassPackage.METHOD:
				sequence_Method(context, (Method) semanticObject); 
				return; 
			case DiagramClassPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case DiagramClassPackage.PACKAGE:
				sequence_Package(context, (org.xtext.smokingtext.diagramclass.diagramClass.Package) semanticObject); 
				return; 
			case DiagramClassPackage.PARAM_IN:
				sequence_paramIn(context, (paramIn) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (classname=ID extension=ID? implements=Implements* (body+=Attribute | body+=Method)*)
	 */
	protected void sequence_Abstract(EObject context, Abstract semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (attributename=ID type=ID birelation=BiRelation?)
	 */
	protected void sequence_Attribute(EObject context, Attribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     linkName=ID
	 */
	protected void sequence_BiRelation(EObject context, BiRelation semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, DiagramClassPackage.Literals.BI_RELATION__LINK_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DiagramClassPackage.Literals.BI_RELATION__LINK_NAME));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getBiRelationAccess().getLinkNameIDTerminalRuleCall_4_0(), semanticObject.getLinkName());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (classname=ID extension=ID? implements=Implements* (body+=Attribute | body+=Method | body+=Dependancy)*)
	 */
	protected void sequence_Class(EObject context, org.xtext.smokingtext.diagramclass.diagramClass.Class semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Dependancy(EObject context, Dependancy semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, DiagramClassPackage.Literals.DEPENDANCY__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DiagramClassPackage.Literals.DEPENDANCY__NAME));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getDependancyAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     classname=ID
	 */
	protected void sequence_Enumeration(EObject context, Enumeration semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, DiagramClassPackage.Literals.ENUMERATION__CLASSNAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DiagramClassPackage.Literals.ENUMERATION__CLASSNAME));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getEnumerationAccess().getClassnameIDTerminalRuleCall_2_0(), semanticObject.getClassname());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (interfacename=ID body+=Method*)
	 */
	protected void sequence_Interface(EObject context, Interface semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID param+=paramIn* returnType=ID?)
	 */
	protected void sequence_Method(EObject context, Method semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     package+=Package*
	 */
	protected void sequence_Model(EObject context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID? classType+=Elements* subPackage+=Package?)
	 */
	protected void sequence_Package(EObject context, org.xtext.smokingtext.diagramclass.diagramClass.Package semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID type=ID)
	 */
	protected void sequence_paramIn(EObject context, paramIn semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, DiagramClassPackage.Literals.PARAM_IN__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DiagramClassPackage.Literals.PARAM_IN__NAME));
			if(transientValues.isValueTransient(semanticObject, DiagramClassPackage.Literals.PARAM_IN__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DiagramClassPackage.Literals.PARAM_IN__TYPE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getParamInAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getParamInAccess().getTypeIDTerminalRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
}
